import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { beforeAll, describe, expect, it } from "vitest";

import { buildServer } from "../../src/server.js";

/**
 * The input schema in `tools/list` is the contract. It is not generated by this
 * codebase — the tool shapes are Zod, the SDK converts them, and Zod decides
 * what the JSON Schema says. So the contract can change without a line of this
 * repository changing, and it has: bumping Zod from 3.25.76 to 4.4.3 drops
 * `additionalProperties: false` from every top-level tool schema. Every test
 * passed, all six CI checks were green, and the published contract had silently
 * stopped saying that unknown arguments are rejected.
 *
 * Zod still strips unknown keys at runtime either way, so that bump was not an
 * injection path. The point is narrower and worse: a host that validates a call
 * against the advertised schema before dispatching would begin accepting
 * arguments the previous schema refused, and nothing anywhere would report it.
 *
 * These assertions exist to make a dependency bump that alters the wire
 * contract fail loudly instead of merging green. They deliberately assert
 * against a real `tools/list` response over a handshake rather than reading the
 * Zod shapes, because what a client receives is the thing under test.
 */

/** No credentials: `buildServer` falls back to an unconfigured provider and
 * still registers every tool, which is exactly what `--list-tools` relies on. */
const ENV: NodeJS.ProcessEnv = {};

const EXPECTED_TOOLS = [
  "netbox_global_search",
  "netbox_discover",
  "netbox_describe",
  "netbox_read",
  "netbox_write",
  "netbox_invoke",
];

interface ListedTool {
  name: string;
  inputSchema: Record<string, unknown>;
  annotations?: Record<string, unknown> | undefined;
}

let tools: ListedTool[];

beforeAll(async () => {
  const server = buildServer(ENV, {});
  const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
  const client = new Client({ name: "schema-contract", version: "0.0.0" });
  await Promise.all([server.connect(serverTransport), client.connect(clientTransport)]);
  try {
    const result = await client.listTools();
    tools = result.tools;
  } finally {
    await client.close();
    await server.close();
  }
});

describe("tools/list input schemas", () => {
  it("advertises exactly the six layered tools", () => {
    expect(tools.map((t) => t.name).sort()).toEqual([...EXPECTED_TOOLS].sort());
  });

  it.each(EXPECTED_TOOLS)("%s rejects unknown arguments", (name) => {
    const tool = tools.find((t) => t.name === name);
    expect(tool, `${name} is not in tools/list`).toBeDefined();

    // The assertion the Zod 4 bump would have failed. `false` specifically —
    // an absent key is not equivalent, because absence is what "unknown
    // properties are allowed" looks like in JSON Schema.
    expect(
      tool?.inputSchema["additionalProperties"],
      `${name} no longer declares additionalProperties: false. A dependency ` +
        `that changes JSON Schema generation can cause this without any change ` +
        `to this repository — check the Zod version before changing this test.`,
    ).toBe(false);
  });

  it.each(EXPECTED_TOOLS)("%s declares an object schema with properties", (name) => {
    const schema = tools.find((t) => t.name === name)?.inputSchema;
    expect(schema?.["type"]).toBe("object");
    expect(Object.keys(schema?.["properties"] ?? {}).length).toBeGreaterThan(0);
  });

  it("never exposes a path, url or endpoint argument on the execution tools", () => {
    // The registry, not the caller, decides the endpoint. This is the property
    // that closes path traversal by construction, and it is worth asserting on
    // the published schema rather than trusting the implementation to stay put.
    for (const name of ["netbox_read", "netbox_write", "netbox_invoke"]) {
      const properties = (tools.find((t) => t.name === name)?.inputSchema["properties"] ??
        {}) as Record<string, unknown>;
      for (const forbidden of ["path", "url", "endpoint", "uri"]) {
        expect(Object.keys(properties), `${name} exposes "${forbidden}"`).not.toContain(
          forbidden,
        );
      }
    }
  });

  it("keeps the read/write annotation split honest", () => {
    const read = tools.find((t) => t.name === "netbox_read")?.annotations;
    const write = tools.find((t) => t.name === "netbox_write")?.annotations;

    // A host that gates on annotations — ChatGPT desktop's "writes" approval
    // mode is one — depends on these being accurate, not conservative.
    expect(read?.["readOnlyHint"]).toBe(true);
    expect(read?.["destructiveHint"]).toBe(false);
    expect(write?.["readOnlyHint"]).toBe(false);
    expect(write?.["destructiveHint"]).toBe(true);
  });
});
